import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import { AuthProvider } from './useAuth'
import { getServerSession } from 'next-auth'
import { redirect } from 'next/navigation'
import { AuthProvider } from '../../components/SessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export  default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession()

  if(session){
    redirect('/')
  }

  return (<>{children}</>)
}
