import { AutoLogoutProvider } from "@/components/AutoLogoutProvider";
import Layout from "@/components/Layout";

import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export  default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession()

  if(!session){
    redirect('/login')
  }

  return (
    <AutoLogoutProvider>
      <Layout>{children}</Layout>
    </AutoLogoutProvider>
  )
}
