import './globals.css'
import "./data-tables-css.css";
import "./satoshi.css";
import type { Metadata } from 'next'
import { AuthProvider } from '@/components/SessionProvider'
import { getServerSession } from 'next-auth'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export  default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession()

  return (
    <html lang="en">
      <AuthProvider session={session}>
        <body>{children}</body>
      </AuthProvider>
    </html>
  )
}
